name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.buildnumber.outputs.build_number }}
      SHA_SHORT: ${{ steps.commithash.outputs.sha_short }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set outputs
        id: commithash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{ secrets.github_token }}
          

  buildMatrix:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
  
    strategy:
        fail-fast: false
        matrix:
          include:
          - os: ubuntu-latest
            filemap: |
              target/release/bundle/appimage/uploaddesktop_0.1.0_amd64.AppImage>uploaddesktop_0.1.0_amd64.AppImage
              target/release/deb/uploaddesktop_0.1.0_amd64.deb>uploaddesktop_0.1.0_amd64.deb
                         
          - os: windows-latest
            filemap: |
              target/release/bundle/msi/uploaddesktop_0.1.0_x64_en-US.msi>uploaddesktop_0.1.0_x64_en-US.msi
            
          - os: macos-latest
            filemap: |
              target/release/bundle/macos/uploaddesktop.app>uploaddesktop.app
              target/release/dmg/uploaddesktop_0.1.0_x64.dmg>uploaddesktop_0.1.0_x64.dmg

    needs: prepare

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16
        
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install rust cache
      uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true

    - name: Install tauri-cli
      uses: baptiste0928/cargo-install@v1
      with:
        crate: tauri-cli
        version: "^1.0.0-rc"
        
    - name: install webkit2gtk (ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0
        
    - name: install app dependencies
      run: cd frontend; yarn
      
    - name: Build
      run: cargo tauri build

    - name: Pipe files to release
      uses: KotwOSS/pipe-to-release@2.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

        filemap: ${{ matrix.filemap }}

        skip_errors: true

        draft: true
        prerelease: true

        tag: "build_${{ needs.prepare.outputs.BUILD_ID }}"
        release_name: "build:${{ needs.prepare.outputs.SHA_SHORT }}"
        release_body: "This is an automated build"
