name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.buildnumber.outputs.build_number }}
      COMMIT: ${{ steps.vars.outputs.sha_short }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{ secrets.github_token }}
          
  buildMatrix:
    strategy:
        fail-fast: false
        matrix:
          platform: [macos-latest, ubuntu-latest, windows-latest]
          include:
          - os: ubuntu-latest
            artifact_name: target/release/bundle/appimage/uploaddesktop_0.1.0_amd64.AppImage
                         | target/release/bundle/deb/uploaddesktop_0.1.0_amd64.deb
                         
          - os: windows-latest
            artifact_name: target/release/bundle/exe/uploaddesktop_0.1.0_x64.exe
            
          - os: macos-latest
            artifact_name: target/release/bundle/macos/uploaddesktop.app
                         | target/release/bundle/dmg/uploaddesktop_0.1.0_x64.dmg

    runs-on: ${{ matrix.platform }}

    needs: prepare

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16
        
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - uses: Swatinem/rust-cache@v1.3.0


    - name: Install tauri-cli
      uses: baptiste0928/cargo-install@v1
      with:
        crate: tauri-cli
        version: "^1.0.0-rc"
        
    - name: install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0
        
    - name: install app dependencies
      run: cd frontend; yarn
      
    - name: Build
      run: cargo tauri build
    
    - name: Upload binaries to release (ubuntu)
      if: matrix.platform == 'ubuntu-latest'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        
        file: ${{ matrix.artifact_name }}
        
        file-glob: true
        
        prerelease: true
        release_name: "build:${{ needs.prepare.outputs.COMMIT }}"
        tag: "build_${{ needs.prepare.outputs.BUILD_ID }}"
        overwrite: true
        body: "This is a prerelease" 
